name: Fuel price bot

on:
  schedule:
    - cron: "31 20 * * *"   # 20:00 Belgium (UTC+1)

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
     
      - name: Test connectivity to PDF
        run: |
          echo "Checking if PDF is reachable..."
          curl -I https://economie.fgov.be/sites/default/files/Files/Energy/prices/Tarifs-officiels-produits-petroliers.pdf


      - name: Install dependencies
        run: pip install requests pdfplumber sendgrid

      - name: Run script
        run: python fuel.py
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
